import { useState } from "react";
import { useLocation } from "wouter";
import { ArrowLeft, BookOpen, Bot, Check, Code2, Copy, GitBranch, Play, ShieldCheck, Workflow } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { NOVA_API_ENDPOINTS, NOVA_API_PLAYGROUND_EXAMPLE, NOVA_ASSISTANT_CONCEPTS } from "@/lib/apiDocsCatalog";

export default function ApiDocsPage() {
  const [, navigate] = useLocation();
  const [copied, setCopied] = useState(false);
  const copyExample = async () => {
    try {
      await navigator.clipboard.writeText(NOVA_API_PLAYGROUND_EXAMPLE);
      setCopied(true);
      setTimeout(() => setCopied(false), 1800);
      toast.success("Playground example copied");
    } catch {
      toast.error("Copy is unavailable in this browser");
    }
  };
  const draftToast = (label: string) => toast.message(`${label} is a safe foundation for the next NovaAI release.`);

  return <main className="min-h-screen bg-[#070a12] text-slate-100">
    <header className="sticky top-0 z-20 border-b border-white/10 bg-[#070a12]/90 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6"><button onClick={() => navigate("/")} className="flex items-center gap-2 text-sm font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-lg border border-violet-300/20 bg-violet-400/10 text-violet-200"><Code2 className="h-4 w-4" /></span>NovaAI <span className="font-normal text-slate-500">Developer</span></button><div className="flex gap-2"><Button variant="ghost" size="sm" onClick={() => navigate("/chat")} className="text-slate-300 hover:bg-white/5 hover:text-white">Open chat</Button><Button size="sm" onClick={() => draftToast("API access request")} className="bg-violet-500 hover:bg-violet-400">Request access</Button></div></div></header>
    <section className="border-b border-white/10"><div className="mx-auto grid max-w-6xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:py-24"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-400/5 px-3 py-1 text-xs font-medium text-cyan-100"><BookOpen className="h-3.5 w-3.5" /> Developer foundation</div><h1 className="max-w-3xl text-4xl font-semibold tracking-[-.04em] text-white sm:text-6xl">Build with the same private context that powers NovaAI.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400">These foundations describe workspace-scoped contracts, a safe playground direction, reusable assistants, and reviewable agent workflows. Provider keys stay server-side; use the vault for sensitive values.</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={() => navigate("/chat")} className="bg-violet-500 hover:bg-violet-400"><Play className="mr-2 h-4 w-4" /> Try in chat</Button><Button variant="outline" onClick={() => navigate("/workspace")} className="border-white/15 bg-transparent text-slate-200 hover:bg-white/5"><Code2 className="mr-2 h-4 w-4" /> Open workspace</Button></div></div><div className="rounded-2xl border border-white/10 bg-gradient-to-br from-violet-500/10 to-cyan-400/5 p-6 shadow-2xl shadow-violet-950/30"><div className="flex items-center gap-3"><ShieldCheck className="h-5 w-5 text-emerald-300" /><p className="font-medium text-white">Private by default</p></div><ul className="mt-5 space-y-4 text-sm leading-6 text-slate-400"><li className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-violet-300" />Every request is scoped to the active NovaAI workspace.</li><li className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-violet-300" />Provider credentials are configured privately, not passed through UI examples.</li><li className="flex gap-3"><Check className="mt-1 h-4 w-4 shrink-0 text-violet-300" />External publishing and destructive workflow steps require an explicit approval design.</li></ul></div></div></section>
    <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6"><div className="grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><aside className="space-y-2"><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-300">Reference</p><h2 className="text-2xl font-semibold tracking-tight text-white">Core contracts</h2><p className="text-sm leading-6 text-slate-400">Use tRPC contracts internally today. A public API gateway can later apply user-issued credentials, rate limits, and auditable scopes.</p><Button variant="ghost" className="mt-2 px-0 text-slate-300 hover:bg-transparent hover:text-white" onClick={() => navigate("/settings")}><ArrowLeft className="mr-2 h-4 w-4" /> Privacy settings</Button></aside><div className="overflow-hidden rounded-2xl border border-white/10 bg-[#0b1020]">{NOVA_API_ENDPOINTS.map((endpoint, index) => <div key={endpoint.path} className={`p-5 ${index ? "border-t border-white/10" : ""}`}><div className="flex flex-wrap items-center gap-3"><span className="rounded bg-emerald-300/10 px-2 py-1 font-mono text-xs font-semibold text-emerald-200">{endpoint.method}</span><code className="text-sm text-white">{endpoint.path}</code></div><p className="mt-3 text-sm leading-6 text-slate-400">{endpoint.description}</p></div>)}</div></div>
      <div className="mt-14 grid gap-8 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-[#0b1020] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-300">Playground</p><h2 className="mt-2 text-xl font-semibold text-white">Typed request seed</h2></div><Button variant="ghost" size="icon" onClick={copyExample} className="text-slate-300 hover:bg-white/5 hover:text-white" title="Copy example">{copied ? <Check className="h-4 w-4 text-emerald-300" /> : <Copy className="h-4 w-4" />}</Button></div><pre className="mt-5 overflow-x-auto rounded-xl border border-white/10 bg-black/30 p-4 text-xs leading-6 text-cyan-100"><code>{NOVA_API_PLAYGROUND_EXAMPLE}</code></pre><Button variant="outline" className="mt-4 w-full border-white/15 bg-transparent text-slate-200 hover:bg-white/5" onClick={() => draftToast("Interactive playground")}><Play className="mr-2 h-4 w-4" /> Open playground draft</Button></div><div className="rounded-2xl border border-white/10 bg-[#0b1020] p-5"><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-300">Assistants & agents</p><h2 className="mt-2 text-xl font-semibold text-white">Composable, reviewable work</h2><div className="mt-5 space-y-4">{NOVA_ASSISTANT_CONCEPTS.map((concept, index) => <button key={concept.title} onClick={() => draftToast(concept.title)} className="group flex w-full items-start gap-3 rounded-xl border border-white/5 bg-white/[.025] p-3 text-left transition hover:border-violet-300/25 hover:bg-violet-400/[.04]"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-violet-400/10 text-violet-200">{index === 0 ? <Bot className="h-4 w-4" /> : index === 1 ? <Workflow className="h-4 w-4" /> : <GitBranch className="h-4 w-4" />}</span><span><span className="block text-sm font-medium text-white">{concept.title}</span><span className="mt-1 block text-xs leading-5 text-slate-400">{concept.text}</span></span></button>)}</div></div></div>
    </section>
  </main>;
}
