import { ArrowLeft, Code2, LockKeyhole, Orbit, ShieldCheck, Sparkles, UserRound } from "lucide-react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { VIRGO_AUTHOR_PROFILE } from "@/lib/virgoAuthorProfile";

const principleIcons = [LockKeyhole, Code2, Sparkles] as const;

export default function VirgoYTPage() {
  const [, navigate] = useLocation();

  return <main className="min-h-screen overflow-x-hidden bg-[#070b16] text-slate-100">
    <div aria-hidden className="pointer-events-none fixed inset-0 -z-0 overflow-hidden"><div className="absolute -left-40 top-10 h-[35rem] w-[35rem] rounded-full bg-violet-600/15 blur-[120px]" /><div className="absolute -right-48 bottom-0 h-[30rem] w-[30rem] rounded-full bg-cyan-500/10 blur-[120px]" /><div className="absolute inset-0 opacity-[0.14] [background-image:linear-gradient(rgba(148,163,184,.15)_1px,transparent_1px),linear-gradient(90deg,rgba(148,163,184,.15)_1px,transparent_1px)] [background-size:4rem_4rem]" /></div>
    <header className="sticky top-0 z-20 border-b border-white/5 bg-[#070b16]/80 backdrop-blur-xl"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6"><button onClick={() => navigate("/")} className="flex items-center gap-2 text-left"><span className="grid h-9 w-9 place-items-center rounded-xl border border-violet-300/25 bg-violet-400/10 text-violet-200"><Orbit className="h-5 w-5" /></span><span className="font-semibold tracking-tight">Nova<span className="text-violet-300">AI</span></span></button><Button variant="ghost" size="sm" onClick={() => navigate("/")} className="text-slate-300 hover:bg-white/5 hover:text-white"><ArrowLeft className="mr-2 h-4 w-4" /> Back to NovaAI</Button></div></header>
    <section className="relative z-10 mx-auto max-w-6xl px-4 pb-16 pt-16 sm:px-6 sm:pb-24 sm:pt-24"><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div><div className="inline-flex items-center gap-2 rounded-full border border-violet-300/20 bg-violet-400/10 px-3 py-1.5 text-xs font-medium text-violet-200"><ShieldCheck className="h-3.5 w-3.5" /> Author documentation</div><p className="mt-6 text-sm font-medium text-cyan-200">Created by {VIRGO_AUTHOR_PROFILE.name}</p><h1 className="mt-3 max-w-3xl text-balance text-5xl font-semibold tracking-[-.055em] text-white sm:text-6xl">{VIRGO_AUTHOR_PROFILE.headline}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-400 sm:text-lg">{VIRGO_AUTHOR_PROFILE.statement}</p><div className="mt-8 flex flex-wrap gap-3"><Button onClick={() => navigate("/chat")} className="bg-violet-500 shadow-[0_0_24px_rgba(139,92,246,.28)] hover:bg-violet-400">Explore NovaAI</Button><Button variant="outline" onClick={() => navigate("/workspace")} className="border-white/15 bg-white/[.03] text-slate-100 hover:bg-white/[.08] hover:text-white">Open workspace</Button></div></div><aside className="rounded-[2rem] border border-violet-300/15 bg-gradient-to-br from-violet-400/[.15] via-[#10172a] to-cyan-400/[.08] p-6 shadow-2xl shadow-black/30 sm:p-8"><div className="grid h-20 w-20 place-items-center rounded-3xl border border-violet-200/20 bg-violet-400/15 text-3xl font-semibold tracking-tight text-violet-100">V</div><p className="mt-6 text-xs font-semibold uppercase tracking-[.18em] text-violet-200">Project author</p><h2 className="mt-2 text-3xl font-semibold tracking-tight text-white">{VIRGO_AUTHOR_PROFILE.name}</h2><p className="mt-2 text-sm text-slate-400">{VIRGO_AUTHOR_PROFILE.role}</p><div className="mt-7 rounded-2xl border border-white/10 bg-black/15 p-4"><div className="flex items-start gap-3"><UserRound className="mt-0.5 h-4 w-4 shrink-0 text-cyan-200" /><p className="text-sm leading-6 text-slate-300">{VIRGO_AUTHOR_PROFILE.attribution}</p></div></div></aside></div></section>
    <section className="relative z-10 border-y border-white/5 bg-[#0a1020]/75"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-300">Creator principles</p><h2 className="mt-3 text-3xl font-semibold tracking-[-.04em] text-white sm:text-4xl">A clear statement of the work behind NovaAI.</h2><p className="mt-4 text-sm leading-6 text-slate-400">This documentation describes the creator attribution and the project direction. It deliberately does not claim unverified awards, affiliations, or personal details.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{VIRGO_AUTHOR_PROFILE.principles.map((principle, index) => { const Icon = principleIcons[index]; return <article key={principle.title} className="rounded-2xl border border-white/8 bg-white/[.025] p-6"><span className="grid h-10 w-10 place-items-center rounded-xl bg-violet-400/10 text-violet-200"><Icon className="h-5 w-5" /></span><h3 className="mt-7 text-lg font-medium text-white">{principle.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{principle.text}</p></article>; })}</div></div></section>
    <section className="relative z-10 mx-auto max-w-6xl px-4 py-16 sm:px-6 sm:py-20"><div className="grid gap-8 rounded-3xl border border-white/10 bg-[#0d1428]/80 p-6 sm:p-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-violet-300">Official presence</p><h2 className="mt-3 text-2xl font-semibold tracking-tight text-white">Creator links are added by approval.</h2></div><p className="text-sm leading-7 text-slate-400">{VIRGO_AUTHOR_PROFILE.officialLinksStatus} This keeps the public author page accurate and prevents unverified accounts from being presented as VirgoYT.</p></div></section>
    <footer className="relative z-10 border-t border-white/5 px-4 py-7 sm:px-6"><div className="mx-auto flex max-w-6xl flex-col gap-2 text-xs text-slate-500 sm:flex-row sm:items-center sm:justify-between"><p>NovaAI by VirgoYT — private intelligence for work that moves.</p><button onClick={() => navigate("/")} className="text-left hover:text-slate-300">Return to NovaAI</button></div></footer>
  </main>;
}
